// examples/react-inmemory/src/App.tsx
import { useSignals } from "@preact/signals-react/runtime";
import { db } from "./data/database";

const users = db.collections.users.findMany({ with: { posts: true } });

function removeUser(id: string) {
  db.collections.users.remove({ id: { $eq: id } });
}

function App() {
  useSignals();
  return (
    <>
      {users.value.map((u) => (
        <div key={u.id}>
          <pre>{JSON.stringify(u, null, 2)}</pre>
          <button onClick={() => removeUser(u.id!)}>remove</button>
        </div>
      ))}
    </>
  );
}

export default App;

// packages/tiki-db-nuxt/playground/app.vue
<template>
  <div v-for="user of users" :key="user.id!">
    <pre>{{ user }}</pre>
    <button
      style="
        background-color: red;
        color: white;
        border: none;
        padding: 6px;
        cursor: pointer;
      "
      @click="removeUser(user.id!)"
    >
      DELETE
    </button>
  </div>
</template>

<script setup lang="ts">
import { db } from "./data/database";
import { seed } from "./data/seed";

const database = await useDatabase(db);

if (import.meta.server) {
  seed(database);
}

const users = computed(
  () => database.collections.users.findMany({ with: { posts: true } }).value
);

function removeUser(id: string) {
  database.collections.users.remove({
    id: {
      $eq: id,
    },
  });
}
</script>
