// examples/vue_inmemory/src/App.vue
<script setup lang="ts">
import { computed } from "vue";
import { db } from "./data/database";

const users = computed(() =>
  db.collections.users.findMany({ with: { posts: true } }).value
);
</script>

<template>
  <div class="m-auto max-w-lg bg-red-50">
    <pre>{{ users }}</pre>
  </div>
</template>

// examples/react-inmemory/src/App.tsx
import { useSignals } from "@preact/signals-react/runtime";
import { db } from "./data/database";

const users = db.collections.users.findMany({ with: { posts: true } });

function removeUser(id: string) {
  db.collections.users.remove({ id: { $eq: id } });
}

function App() {
  useSignals();
  return (
    <>
      {users.value.map((u) => (
        <div key={u.id}>
          <pre>{JSON.stringify(u, null, 2)}</pre>
          <button onClick={() => removeUser(u.id!)}>remove</button>
        </div>
      ))}
    </>
  );
}

export default App;
