// examples/react-inmemory/src/App.tsx
import { useSignals } from "@preact/signals-react/runtime";
import { db } from "./data/database";

const users = db.collections.users.findMany({ with: { posts: true } });

function removeUser(id: string) {
  db.collections.users.remove({ id: { $eq: id } });
}

function App() {
  useSignals();
  return (
    <>
      {users.value.map((u) => (
        <div key={u.id}>
          <pre>{JSON.stringify(u, null, 2)}</pre>
          <button onClick={() => removeUser(u.id!)}>remove</button>
        </div>
      ))}
    </>
  );
}

export default App;

// packages/nuxt-tiki-db/playground/app.vue
<template>
  <div v-for="user of users" :key="user.id!">
    <pre>{{ user.id }}</pre>
    <button @click="removeUser(user.id!)">DELETE</button>
  </div>
</template>

<script setup lang="ts">
import { db } from "./data/database";
import { seed } from "./data/seed";

const database = useDB(db);
database.init();
if (import.meta.server) {
  seed(database);
}

const users = computed(() => database.collections.users.findMany({}).value);

function removeUser(id: string) {
  database.collections.users.remove({
    id: {
      $eq: id,
    },
  });
}
</script>
